# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

cache: packages

Remotes: Rdatatable/data.table

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

